/**
 * DeepAlias Hunter Pro - Background Script
 * Versão limpa e funcional para Firefox
 */

console.log('🚀 DeepAlias Hunter Pro - Background Script Iniciado');

// Estado da aplicação
var appState = {
    isSearching: false,
    progress: 0,
    results: [],
    currentQuery: null
};

// Plataformas para busca - Base de dados completa expandida v3.1
var platforms = [
    // 🔷 Redes Sociais Principais
    { name: 'Instagram', url: 'https://instagram.com/{username}', icon: '📷', category: 'social', risk: 'low' },
    { name: 'Facebook', url: 'https://facebook.com/{username}', icon: '👥', category: 'social', risk: 'low' },
    { name: 'Twitter', url: 'https://twitter.com/{username}', icon: '🐦', category: 'social', risk: 'low' },
    { name: 'X.com', url: 'https://x.com/{username}', icon: '❌', category: 'social', risk: 'low' },
    { name: 'TikTok', url: 'https://tiktok.com/@{username}', icon: '🎵', category: 'social', risk: 'low' },
    { name: 'YouTube', url: 'https://youtube.com/@{username}', icon: '📺', category: 'social', risk: 'low' },
    { name: 'Snapchat', url: 'https://snapchat.com/add/{username}', icon: '👻', category: 'social', risk: 'low' },
    { name: 'Pinterest', url: 'https://pinterest.com/{username}', icon: '📌', category: 'social', risk: 'low' },
    { name: 'LinkedIn', url: 'https://linkedin.com/in/{username}', icon: '💼', category: 'social', risk: 'low' },
    { name: 'Tumblr', url: 'https://{username}.tumblr.com', icon: '🔵', category: 'social', risk: 'medium' },
    { name: 'Reddit', url: 'https://reddit.com/user/{username}', icon: '🤖', category: 'social', risk: 'low' },
    { name: 'Discord', url: 'https://discord.com/users/{username}', icon: '🎮', category: 'social', risk: 'medium' },
    { name: 'Telegram', url: 'https://t.me/{username}', icon: '✈️', category: 'social', risk: 'medium' },
    { name: 'VK', url: 'https://vk.com/{username}', icon: '🇷🇺', category: 'social', risk: 'low' },
    { name: 'WeHeartIt', url: 'https://weheartit.com/{username}', icon: '💖', category: 'social', risk: 'low' },
    { name: 'Ask.fm', url: 'https://ask.fm/{username}', icon: '❓', category: 'social', risk: 'medium' },
    { name: 'CuriousCat', url: 'https://curiouscat.live/{username}', icon: '🐱', category: 'social', risk: 'medium' },
    { name: 'Yubo', url: 'https://yubo.live/{username}', icon: '💛', category: 'social', risk: 'medium' },
    { name: 'Bigo Live', url: 'https://bigo.tv/{username}', icon: '📹', category: 'social', risk: 'medium' },

    // 🟥 Sites de Conteúdo Adulto e Venda de Conteúdo
    { name: 'OnlyFans', url: 'https://onlyfans.com/{username}', icon: '🔞', category: 'adult', risk: 'high', adult: true, urgent: true },
    { name: 'Privacy.com.br', url: 'https://privacy.com.br/{username}', icon: '🇧🇷', category: 'adult', risk: 'high', adult: true, urgent: true },
    { name: 'Fansly', url: 'https://fansly.com/{username}', icon: '💋', category: 'adult', risk: 'high', adult: true, urgent: true },
    { name: 'JustForFans', url: 'https://justfor.fans/{username}', icon: '🔥', category: 'adult', risk: 'high', adult: true, urgent: true },
    { name: 'FanCentro', url: 'https://fancentro.com/{username}', icon: '💎', category: 'adult', risk: 'high', adult: true },
    { name: 'FanFever', url: 'https://fanfever.com.br/{username}', icon: '🔥', category: 'adult', risk: 'high', adult: true },
    { name: 'CameraPrivé', url: 'https://cameraprive.com/{username}', icon: '📹', category: 'adult', risk: 'high', adult: true },
    { name: 'PepperPlay', url: 'https://pepperplay.com/{username}', icon: '🌶️', category: 'adult', risk: 'high', adult: true },
    { name: 'LoyalFans', url: 'https://loyalfans.com/{username}', icon: '👑', category: 'adult', risk: 'high', adult: true },
    { name: 'Fanvue', url: 'https://fanvue.com/{username}', icon: '🌟', category: 'adult', risk: 'high', adult: true },
    { name: 'ManyVids', url: 'https://manyvids.com/{username}', icon: '🎬', category: 'adult', risk: 'high', adult: true },
    { name: 'AVNStars', url: 'https://avnstars.com/{username}', icon: '⭐', category: 'adult', risk: 'high', adult: true },
    { name: 'IsMyGirl', url: 'https://ismygirl.com/{username}', icon: '💃', category: 'adult', risk: 'high', adult: true },
    { name: 'PocketStars', url: 'https://pocketstars.com/{username}', icon: '🌟', category: 'adult', risk: 'high', adult: true },
    { name: 'Clipp Store', url: 'https://clipp.store/{username}', icon: '🛒', category: 'adult', risk: 'high', adult: true },
    { name: 'IWantClips', url: 'https://iwantclips.com/{username}', icon: '📎', category: 'adult', risk: 'high', adult: true },
    { name: 'ModelHub', url: 'https://modelhub.com/{username}', icon: '🎭', category: 'adult', risk: 'high', adult: true },
    { name: 'AdultWork', url: 'https://adultwork.com/{username}', icon: '💼', category: 'adult', risk: 'high', adult: true },
    { name: 'NaughtyAmerica', url: 'https://naughtyamerica.com/{username}', icon: '🇺🇸', category: 'adult', risk: 'high', adult: true },
    { name: 'UnlokMe', url: 'https://unlok.me/{username}', icon: '🔓', category: 'adult', risk: 'high', adult: true },
    { name: 'NSFWFans', url: 'https://nsfwfans.com/{username}', icon: '🔞', category: 'adult', risk: 'high', adult: true },
    { name: 'PornPayPerView', url: 'https://pornpayperview.com/{username}', icon: '💰', category: 'adult', risk: 'high', adult: true },
    { name: 'EPlay', url: 'https://eplay.com/{username}', icon: '🎮', category: 'adult', risk: 'high', adult: true },
    
    // 🟥 Sites de Cam e Streaming Adulto
    { name: 'Chaturbate', url: 'https://chaturbate.com/{username}', icon: '💬', category: 'cam', risk: 'high', adult: true, urgent: true },
    { name: 'Stripchat', url: 'https://stripchat.com/{username}', icon: '💃', category: 'cam', risk: 'high', adult: true, urgent: true },
    { name: 'LiveJasmin', url: 'https://livejasmin.com/{username}', icon: '🌹', category: 'cam', risk: 'high', adult: true, urgent: true },
    { name: 'MyFreeCams', url: 'https://myfreecams.com/{username}', icon: '🎥', category: 'cam', risk: 'high', adult: true, urgent: true },
    { name: 'BongaCams', url: 'https://bonga.com/{username}', icon: '🥁', category: 'cam', risk: 'high', adult: true, urgent: true },
    { name: 'Cam4', url: 'https://cam4.com/{username}', icon: '📷', category: 'cam', risk: 'high', adult: true, urgent: true },
    { name: 'CamSoda', url: 'https://camsoda.com/{username}', icon: '🥤', category: 'cam', risk: 'high', adult: true, urgent: true },
    { name: 'Camversity', url: 'https://camversity.com/{username}', icon: '🎓', category: 'cam', risk: 'high', adult: true },
    { name: 'Flirt4Free', url: 'https://flirt4free.com/{username}', icon: '😘', category: 'cam', risk: 'high', adult: true },
    { name: 'CamPlace', url: 'https://camplace.com/{username}', icon: '🏠', category: 'cam', risk: 'high', adult: true },
    { name: 'Cams.com', url: 'https://cams.com/{username}', icon: '📹', category: 'cam', risk: 'high', adult: true },
    { name: 'XHamsterLive', url: 'https://xhamsterlive.com/{username}', icon: '🐹', category: 'cam', risk: 'high', adult: true },
    { name: 'XVideosLive', url: 'https://xvideoslive.com/{username}', icon: '🎬', category: 'cam', risk: 'high', adult: true },
    { name: 'CamWhores.tv', url: 'https://camwhores.tv/{username}', icon: '📺', category: 'cam', risk: 'high', adult: true },
    { name: 'CamModelDirectory', url: 'https://cammodeldirectory.com/{username}', icon: '📋', category: 'cam', risk: 'high', adult: true },
    { name: 'OnlyCam', url: 'https://onlycam.com/{username}', icon: '📹', category: 'cam', risk: 'high', adult: true },
    { name: 'JustCamIt', url: 'https://justcamit.com/{username}', icon: '🎥', category: 'cam', risk: 'high', adult: true },
    { name: 'SexCamsPlus', url: 'https://sexcamsplus.com/{username}', icon: '➕', category: 'cam', risk: 'high', adult: true },
    { name: 'HerbicepsCam', url: 'https://herbicepscam.com/{username}', icon: '💪', category: 'cam', risk: 'high', adult: true },
    
    // 🟨 Sites de Portfólio de Modelos / Fotógrafos / Criadores
    { name: 'Behance', url: 'https://behance.net/{username}', icon: '🎨', category: 'portfolio', risk: 'low' },
    { name: 'ArtStation', url: 'https://artstation.com/{username}', icon: '🖼️', category: 'portfolio', risk: 'low' },
    { name: 'ModelMayhem', url: 'https://modelmayhem.com/{username}', icon: '📸', category: 'portfolio', risk: 'medium' },
    { name: 'ViewBug', url: 'https://viewbug.com/{username}', icon: '🐛', category: 'portfolio', risk: 'low' },
    { name: '500px', url: 'https://500px.com/{username}', icon: '📷', category: 'portfolio', risk: 'low' },
    { name: 'Dribbble', url: 'https://dribbble.com/{username}', icon: '🏀', category: 'portfolio', risk: 'low' },
    { name: 'DeviantArt', url: 'https://deviantart.com/{username}', icon: '🎭', category: 'portfolio', risk: 'medium' },
    { name: 'VSCO', url: 'https://vsco.co/{username}', icon: '📱', category: 'portfolio', risk: 'low' },
    { name: 'About.me', url: 'https://about.me/{username}', icon: '👤', category: 'portfolio', risk: 'low' },
    { name: 'Pixpa', url: 'https://{username}.pixpa.com', icon: '🌐', category: 'portfolio', risk: 'low' },
    { name: 'Format', url: 'https://{username}.format.com', icon: '📐', category: 'portfolio', risk: 'low' },
    { name: 'FolioHD', url: 'https://foliohd.com/{username}', icon: '📱', category: 'portfolio', risk: 'low' },
    { name: 'Canva', url: 'https://canva.com/{username}', icon: '🎨', category: 'portfolio', risk: 'low' },
    { name: 'OneModelPlace', url: 'https://onemodelplace.com/{username}', icon: '📸', category: 'portfolio', risk: 'medium' },
    { name: 'PortfolioBox', url: 'https://portfoliobox.net/{username}', icon: '📦', category: 'portfolio', risk: 'low' },
    { name: 'PhotoShelter', url: 'https://photoshelter.com/{username}', icon: '🏠', category: 'portfolio', risk: 'low' },
    { name: 'Zenfolio', url: 'https://zenfolio.com/{username}', icon: '🧘', category: 'portfolio', risk: 'low' },
    { name: 'PhotoDeck', url: 'https://photodeck.com/{username}', icon: '🃏', category: 'portfolio', risk: 'low' },
    { name: 'SmugMug', url: 'https://smugmug.com/{username}', icon: '☕', category: 'portfolio', risk: 'low' },
    { name: 'WordPress', url: 'https://{username}.wordpress.com', icon: '📝', category: 'portfolio', risk: 'low' },
    { name: 'Wix', url: 'https://{username}.wixsite.com', icon: '🏗️', category: 'portfolio', risk: 'low' },
    { name: 'Cargo', url: 'https://cargo.site/{username}', icon: '📦', category: 'portfolio', risk: 'low' },
    { name: 'Carbonmade', url: 'https://{username}.carbonmade.com', icon: '💎', category: 'portfolio', risk: 'low' },
    { name: 'Krop', url: 'https://krop.com/{username}', icon: '🌾', category: 'portfolio', risk: 'low' },
    { name: 'Clippings.me', url: 'https://clippings.me/{username}', icon: '📎', category: 'portfolio', risk: 'low' },
    { name: 'Dunked', url: 'https://dunked.com/{username}', icon: '🏀', category: 'portfolio', risk: 'low' },
    { name: 'Crevado', url: 'https://crevado.com/{username}', icon: '🎨', category: 'portfolio', risk: 'low' },
    { name: 'Yola', url: 'https://yola.com/{username}', icon: '🌐', category: 'portfolio', risk: 'low' },
    { name: 'Weebly', url: 'https://weebly.com/{username}', icon: '🐝', category: 'portfolio', risk: 'low' },
    { name: 'VisualSociety', url: 'https://visualsociety.com/{username}', icon: '👁️', category: 'portfolio', risk: 'low' },
    { name: 'Lightfolio', url: 'https://lightfolio.com/{username}', icon: '💡', category: 'portfolio', risk: 'low' },
    { name: 'SlickPic', url: 'https://slickpic.com/{username}', icon: '📸', category: 'portfolio', risk: 'low' },
    { name: 'Pixieset', url: 'https://pixieset.com/{username}', icon: '🧚', category: 'portfolio', risk: 'low' },
    { name: 'Snapwire', url: 'https://snapwi.re/{username}', icon: '📷', category: 'portfolio', risk: 'low' },
    { name: 'ShootProof', url: 'https://shootproof.com/{username}', icon: '🎯', category: 'portfolio', risk: 'low' },
    { name: 'PicTime', url: 'https://pic-time.com/{username}', icon: '⏰', category: 'portfolio', risk: 'low' },
    
    // 🟦 Sites de Casting / Agências de Modelos
    { name: 'Backstage', url: 'https://backstage.com/{username}', icon: '🎬', category: 'casting', risk: 'medium' },
    { name: 'StarNow', url: 'https://starnow.com/{username}', icon: '⭐', category: 'casting', risk: 'medium' },
    { name: 'CastingNetworks', url: 'https://castingnetworks.com/{username}', icon: '🌐', category: 'casting', risk: 'medium' },
    { name: 'Models.com', url: 'https://models.com/{username}', icon: '👗', category: 'casting', risk: 'medium' },
    { name: 'ActorsAccess', url: 'https://actorsaccess.com/{username}', icon: '🎭', category: 'casting', risk: 'medium' },
    { name: 'CastingFrontier', url: 'https://castingfrontier.com/{username}', icon: '🚀', category: 'casting', risk: 'medium' },
    { name: 'ExploreModeling', url: 'https://exploretalent.com/{username}', icon: '🔍', category: 'casting', risk: 'medium' },
    { name: 'NewFaces', url: 'https://newfaces.com/{username}', icon: '👶', category: 'casting', risk: 'medium' },
    { name: 'ModelScouts', url: 'https://modelscouts.com/{username}', icon: '🕵️', category: 'casting', risk: 'medium' },
    { name: 'TalentHouse', url: 'https://talenthouse.com/{username}', icon: '🏠', category: 'casting', risk: 'medium' },
    { name: 'ModNet.io', url: 'https://modnet.io/{username}', icon: '🌐', category: 'casting', risk: 'medium' },
    { name: 'ModelManagement', url: 'https://modelmanagement.com/{username}', icon: '👔', category: 'casting', risk: 'medium' },
    { name: 'TheCastingNetwork', url: 'https://thecastingnetwork.com/{username}', icon: '🕸️', category: 'casting', risk: 'medium' },
    { name: 'CastingCallHub', url: 'https://castingcallhub.com/{username}', icon: '📞', category: 'casting', risk: 'medium' },
    { name: 'CastItTalent', url: 'https://castittalent.com/{username}', icon: '🎯', category: 'casting', risk: 'medium' },
    { name: 'CastingNowUK', url: 'https://castingnow.co.uk/{username}', icon: '🇬🇧', category: 'casting', risk: 'medium' },
    { name: 'AllCasting', url: 'https://allcasting.com/{username}', icon: '🎭', category: 'casting', risk: 'medium' },
    { name: 'ModelWire', url: 'https://modelwire.com/{username}', icon: '📡', category: 'casting', risk: 'medium' },
    { name: 'ModelBookings', url: 'https://modelbookings.com/{username}', icon: '📅', category: 'casting', risk: 'medium' },
    { name: 'CastingElite', url: 'https://castingelite.com/{username}', icon: '👑', category: 'casting', risk: 'medium' },
    { name: 'Talentt', url: 'https://talentt.com/{username}', icon: '🎪', category: 'casting', risk: 'medium' },
    { name: 'EliteModelWorld', url: 'https://elitemodelworld.com/{username}', icon: '🌍', category: 'casting', risk: 'medium' },
    { name: 'Wilhelmina', url: 'https://wilhelmina.com/{username}', icon: '👸', category: 'casting', risk: 'medium' },
    { name: 'FordModels', url: 'https://fordmodels.com/{username}', icon: '🚗', category: 'casting', risk: 'medium' },
    { name: 'IMGModels', url: 'https://imgmodels.com/{username}', icon: '🖼️', category: 'casting', risk: 'medium' },
    { name: 'NextManagement', url: 'https://nextmanagement.com/{username}', icon: '⏭️', category: 'casting', risk: 'medium' },
    { name: 'DNAModels', url: 'https://dna-models.com/{username}', icon: '🧬', category: 'casting', risk: 'medium' },
    
    // 🟧 Sites/Fóruns de Acompanhantes / Anúncios / Encontros  
    { name: 'FatalModel', url: 'https://fatalmodel.com/{username}', icon: '💀', category: 'escort', risk: 'high', adult: true, urgent: true },
    { name: 'Skokka', url: 'https://skokka.com/{username}', icon: '💄', category: 'escort', risk: 'high', adult: true, urgent: true },
    { name: 'Lupanares', url: 'https://lupanares.com/{username}', icon: '🏠', category: 'escort', risk: 'high', adult: true, urgent: true },
    { name: 'Meetes', url: 'https://meetes.com/{username}', icon: '🤝', category: 'escort', risk: 'high', adult: true },
    { name: 'AnunciArt', url: 'https://anunciart.com/{username}', icon: '📢', category: 'escort', risk: 'high', adult: true },
    { name: 'EasyCompanions', url: 'https://easycompanions.com/{username}', icon: '👫', category: 'escort', risk: 'high', adult: true },
    { name: 'VivaStreet', url: 'https://vivastreet.com/{username}', icon: '🚶', category: 'escort', risk: 'high', adult: true },
    { name: 'Locanto', url: 'https://locanto.com/{username}', icon: '📍', category: 'escort', risk: 'high', adult: true },
    { name: 'MileRoticos', url: 'https://mileroticos.com/{username}', icon: '🌶️', category: 'escort', risk: 'high', adult: true },
    { name: 'Gatas.com', url: 'https://gatas.com/{username}', icon: '🐱', category: 'escort', risk: 'high', adult: true },
    { name: 'GPOnline', url: 'https://gponline.net/{username}', icon: '💻', category: 'escort', risk: 'high', adult: true },
    { name: 'Terapeuta.net', url: 'https://terapeuta.net/{username}', icon: '💆', category: 'escort', risk: 'high', adult: true },
    { name: 'CityOfLove', url: 'https://cityoflove.com/{username}', icon: '💕', category: 'escort', risk: 'high', adult: true },
    { name: 'MassageRepublic', url: 'https://massage-republic.com/{username}', icon: '💆‍♀️', category: 'escort', risk: 'high', adult: true },
    { name: 'EuroGirlsEscort', url: 'https://eurogirlsescort.com/{username}', icon: '🇪🇺', category: 'escort', risk: 'high', adult: true },
    { name: 'Hot.com.br', url: 'https://hot.com.br/{username}', icon: '🔥', category: 'escort', risk: 'high', adult: true },
    { name: 'BrHookup', url: 'https://br.hookup.com/{username}', icon: '🪝', category: 'escort', risk: 'high', adult: true },
    { name: 'EncontreUmGaroto', url: 'https://encontreumgaroto.com/{username}', icon: '👦', category: 'escort', risk: 'high', adult: true },
    { name: 'Companheiros.net', url: 'https://companheiros.net/{username}', icon: '🤝', category: 'escort', risk: 'high', adult: true },
    
    // 🟪 Sites de Compartilhamento de Imagens Sensíveis
    { name: 'Imgur', url: 'https://imgur.com/user/{username}', icon: '🖼️', category: 'images', risk: 'medium' },
    { name: 'ImageFap', url: 'https://imagefap.com/{username}', icon: '📸', category: 'images', risk: 'high', adult: true },
    { name: 'Motherless', url: 'https://motherless.com/{username}', icon: '🚫', category: 'images', risk: 'high', adult: true },
    { name: 'E621', url: 'https://e621.net/{username}', icon: '🦊', category: 'images', risk: 'high', adult: true },
    { name: 'FurAffinity', url: 'https://furaffinity.net/user/{username}', icon: '🦊', category: 'images', risk: 'medium', adult: true },
    { name: 'Rule34.xxx', url: 'https://rule34.xxx/{username}', icon: '🔞', category: 'images', risk: 'high', adult: true },
    { name: 'Rule34Paheal', url: 'https://rule34.paheal.net/{username}', icon: '🎭', category: 'images', risk: 'high', adult: true },
    { name: 'XBooru', url: 'https://xbooru.com/{username}', icon: '📚', category: 'images', risk: 'high', adult: true },
    { name: 'Gelbooru', url: 'https://gelbooru.com/{username}', icon: '🟦', category: 'images', risk: 'high', adult: true },
    { name: 'Danbooru', url: 'https://danbooru.donmai.us/{username}', icon: '🟫', category: 'images', risk: 'high', adult: true },
    { name: 'HypnoHub', url: 'https://hypnohub.net/{username}', icon: '🌀', category: 'images', risk: 'high', adult: true },
    { name: 'HentaiFoundry', url: 'https://hentai-foundry.com/{username}', icon: '⚒️', category: 'images', risk: 'high', adult: true },
    { name: '8Muses', url: 'https://8muses.com/{username}', icon: '🎭', category: 'images', risk: 'high', adult: true },
    { name: 'Pixiv', url: 'https://pixiv.net/users/{username}', icon: '🎨', category: 'images', risk: 'medium', adult: true },
    { name: 'NHentai', url: 'https://nhentai.net/{username}', icon: '📚', category: 'images', risk: 'high', adult: true },
    { name: 'PornPics', url: 'https://pornpics.com/{username}', icon: '📸', category: 'images', risk: 'high', adult: true },
    { name: 'PornImg', url: 'https://pornimg.com/{username}', icon: '🖼️', category: 'images', risk: 'high', adult: true },
    { name: 'LeakGirls', url: 'https://leakgirls.com/{username}', icon: '💧', category: 'images', risk: 'high', adult: true, urgent: true },
    { name: 'R18.com', url: 'https://r18.com/{username}', icon: '🔞', category: 'images', risk: 'high', adult: true },
    { name: 'SuperHQ', url: 'https://superhq.net/{username}', icon: '🦸', category: 'images', risk: 'high', adult: true },
    
    // 🔗 Link in Bio Platforms
    { name: 'Linktree', url: 'https://linktr.ee/{username}', icon: '🌳', category: 'linkinbio', risk: 'low' },
    { name: 'Beacons.ai', url: 'https://beacons.ai/{username}', icon: '🔗', category: 'linkinbio', risk: 'low' },
    { name: 'Carrd', url: 'https://{username}.carrd.co', icon: '🎴', category: 'linkinbio', risk: 'low' },
    
    // 📚 Plataformas de Desenvolvimento
    { name: 'GitHub', url: 'https://github.com/{username}', icon: '📚', category: 'dev', risk: 'low' },
    { name: 'GitLab', url: 'https://gitlab.com/{username}', icon: '🦊', category: 'dev', risk: 'low' },
    { name: 'CodePen', url: 'https://codepen.io/{username}', icon: '✒️', category: 'dev', risk: 'low' },
    { name: 'Stack Overflow', url: 'https://stackoverflow.com/users/{username}', icon: '📚', category: 'dev', risk: 'low' },
    
    // 🎵 Plataformas de Música e Audio
    { name: 'Spotify', url: 'https://open.spotify.com/user/{username}', icon: '🎵', category: 'music', risk: 'low' },
    { name: 'SoundCloud', url: 'https://soundcloud.com/{username}', icon: '☁️', category: 'music', risk: 'low' },
    { name: 'Bandcamp', url: 'https://{username}.bandcamp.com', icon: '🎸', category: 'music', risk: 'low' },
    { name: 'Last.fm', url: 'https://last.fm/user/{username}', icon: '🎧', category: 'music', risk: 'low' },
    
    // 🎮 Plataformas Gaming
    { name: 'Twitch', url: 'https://twitch.tv/{username}', icon: '🎮', category: 'gaming', risk: 'medium' },
    { name: 'Steam', url: 'https://steamcommunity.com/id/{username}', icon: '🎯', category: 'gaming', risk: 'low' },
    { name: 'Xbox Live', url: 'https://account.xbox.com/profile?gamertag={username}', icon: '🎮', category: 'gaming', risk: 'low' },
    { name: 'PlayStation', url: 'https://psnprofiles.com/{username}', icon: '🎮', category: 'gaming', risk: 'low' },
    
    // 🛒 Sites de E-commerce/Freelance
    { name: 'Fiverr', url: 'https://fiverr.com/{username}', icon: '💸', category: 'freelance', risk: 'low' },
    { name: 'Upwork', url: 'https://upwork.com/freelancers/{username}', icon: '💼', category: 'freelance', risk: 'low' },
    { name: 'Etsy', url: 'https://etsy.com/shop/{username}', icon: '🛍️', category: 'shop', risk: 'low' },
    { name: 'eBay', url: 'https://ebay.com/usr/{username}', icon: '🏪', category: 'shop', risk: 'low' },
    
    // 🌐 Sites Regionais Brasil
    { name: 'Kwai', url: 'https://kwai.com/@{username}', icon: '📱', category: 'social', risk: 'medium' },
    { name: 'Orkut', url: 'https://orkut.br.com/{username}', icon: '🔵', category: 'social', risk: 'low' },
    { name: 'Badoo', url: 'https://badoo.com/{username}', icon: '💘', category: 'dating', risk: 'medium' },
    { name: 'Tinder', url: 'https://tinder.com/@{username}', icon: '🔥', category: 'dating', risk: 'medium' },
    { name: 'Bumble', url: 'https://bumble.com/{username}', icon: '🐝', category: 'dating', risk: 'medium' },
    
    // 💰 Sites de Investimento/Crypto
    { name: 'Binance', url: 'https://binance.com/en/user/{username}', icon: '₿', category: 'crypto', risk: 'medium' },
    { name: 'Coinbase', url: 'https://coinbase.com/{username}', icon: '🪙', category: 'crypto', risk: 'medium' },
    { name: 'Bitcoin Talk', url: 'https://bitcointalk.org/index.php?action=profile;u={username}', icon: '₿', category: 'crypto', risk: 'medium' },
    
    // 📰 Sites de Blog/Notícias
    { name: 'Medium', url: 'https://medium.com/@{username}', icon: '📝', category: 'blog', risk: 'low' },
    { name: 'Substack', url: 'https://{username}.substack.com', icon: '📰', category: 'blog', risk: 'low' },
    { name: 'Blogger', url: 'https://{username}.blogspot.com', icon: '📖', category: 'blog', risk: 'low' },
    
    // 🎪 Sites Diversos
    { name: 'Clubhouse', url: 'https://clubhouse.com/@{username}', icon: '🎪', category: 'social', risk: 'low' },
    { name: 'Mastodon', url: 'https://mastodon.social/@{username}', icon: '🐘', category: 'social', risk: 'low' },
    { name: 'Truth Social', url: 'https://truthsocial.com/@{username}', icon: '🗣️', category: 'social', risk: 'low' },
    { name: 'Gettr', url: 'https://gettr.com/user/{username}', icon: '🔊', category: 'social', risk: 'low' }
];
