// Extensões e variações de username para busca - EXPANDIDO v3.2
function generateUsernameVariations(username) {
    var variations = [
        username,
        username.toLowerCase(),
        username.toUpperCase(),
        
        // Variações com símbolos comuns
        username + '_',
        '_' + username,
        username + 'x',
        'x' + username,
        username + '.',
        '.' + username,
        username + '-',
        '-' + username,
        username + '.oficial',
        username + '.official',
        username + '.real',
        username + '.vip',
        username + '_oficial',
        username + '_official',
        username + '_real',
        username + '_vip',
        
        // Variações com números comuns no Brasil
        username + '69',
        username + '18',
        username + '21',
        username + '22',
        username + '23',
        username + '24',
        username + '25',
        username + '2024',
        username + '2025',
        '2024' + username,
        '2025' + username,
        username + '01',
        username + '1',
        username + '2',
        username + '3',
        '1' + username,
        '2' + username,
        username + '007',
        username + '171',
        username + '71',
        username + '33',
        username + '88',
        username + '55',
        username + '10',
        username + '100',
        
        // Variações profissionais/oficiais
        username + 'official',
        'official' + username,
        'real' + username,
        username + 'real',
        username + 'vip',
        'vip' + username,
        username + 'model',
        'model' + username,
        username + 'pro',
        'pro' + username,
        username + 'elite',
        'elite' + username,
        username + 'original',
        'original' + username,
        username + 'verified',
        'verified' + username,
        username + 'oficial',
        'oficial' + username,
        username + 'br',
        'br' + username,
        username + 'brasil',
        'brasil' + username,
        
        // Variações de cam/adult
        username + 'cam',
        'cam' + username,
        username + 'live',
        'live' + username,
        username + 'shows',
        username + 'xxx',
        'xxx' + username,
        username + 'hot',
        'hot' + username,
        username + 'sexy',
        'sexy' + username,
        username + 'adoro',
        username + 'love',
        username + 'sex',
        'sex' + username,
        username + 'fire',
        username + 'fogo',
        username + 'gata',
        'gata' + username,
        username + 'gato',
        'gato' + username,
        username + 'tesao',
        username + 'tesuda',
        username + 'sensual',
        'sensual' + username,
        
        // Variações de plataformas específicas
        username + 'onlyfans',
        username + 'of',
        'of' + username,
        username + 'fansly',
        username + 'privacy',
        username + 'fancentro',
        username + 'manyvids',
        username + 'chaturbate',
        username + 'cb',
        'cb' + username,
        username + 'cam4',
        username + 'stripchat',
        username + 'insta',
        username + 'ig',
        'ig' + username,
        username + 'tt',
        'tt' + username,
        username + 'tw',
        'tw' + username,
        username + 'fb',
        'fb' + username,
        username + 'premium',
        'premium' + username,
        username + 'free',
        'free' + username,
        
        // Variações backup/alternativas
        username + '.backup',
        'backup.' + username,
        username + 'backup',
        'backup' + username,
        username + 'alt',
        'alt' + username,
        username + '2nd',
        username + 'second',
        username + 'new',
        'new' + username,
        username + 'priv',
        'priv' + username,
        username + 'private',
        'private' + username,
        username + '.new',
        'new.' + username,
        username + '.alt',
        'alt.' + username,
        username + '_new',
        'new_' + username,
        username + '_alt',
        'alt_' + username,
        username + '_backup',
        'backup_' + username,
        username + '_2',
        username + '2',
        
        // Variações regionais
        username + 'br',
        'br' + username,
        username + 'brasil',
        'brasil' + username,
        username + 'usa',
        username + 'uk',
        username + 'eu',
        username + 'pt',
        username + 'es',
        username + 'jp',
        username + 'fr',
        username + 'de',
        username + 'ru',
        username + 'arg',
        username + 'mx',
        username + 'cl',
        username + 'rio',
        username + 'sp',
        username + 'mg',
        username + 'rj',
        
        // Variações de ocupações e nicho
        username + 'model',
        username + 'models',
        username + 'modeling',
        username + 'modelling',
        username + 'photo',
        username + 'photography',
        username + 'photos',
        username + 'pics',
        username + 'art',
        username + 'arts',
        username + 'artist',
        username + 'shoot',
        username + 'shoots',
        username + 'modelo',
        username + 'modelando',
        username + 'performer',
        username + 'atriz',
        username + 'ator',
        username + 'acompanhante',
        username + 'massagens',
        username + 'massagem',
        username + 'terapeuta',
        username + 'terapias',
        
        // Limpeza de caracteres
        username.replace(/\d+/g, ''), // remove números
        username.replace(/[^a-zA-Z0-9]/g, ''), // remove caracteres especiais
        username.replace(/[_\-\.]/g, ''), // remove separadores
        
        // Duplicações parciais
        username + username.slice(-2),
        username.slice(0, -2) + username,
        username + username.charAt(0),
        username.charAt(0) + username,
        username + username,
        username.charAt(0) + username.charAt(0) + username,
        username + username.charAt(0) + username.charAt(0),
        
        // Substituições comuns de caracteres
        username.replace(/a/g, '4'),
        username.replace(/e/g, '3'),
        username.replace(/i/g, '1'),
        username.replace(/o/g, '0'),
        username.replace(/s/g, '5'),
        username.replace(/t/g, '7'),
        
        // Combinações de transformações
        username.toLowerCase().replace(/a/g, '4'),
        username.toLowerCase().replace(/e/g, '3'),
        username.toLowerCase().replace(/i/g, '1'),
        username.toLowerCase().replace(/o/g, '0'),
        username.toLowerCase().replace(/s/g, '5'),
        username.toLowerCase().replace(/t/g, '7'),
        
        // Reordenação de caracteres se o username tiver espaços
        username.split(' ').reverse().join(''),
        username.split(' ').reverse().join('_'),
        username.split(' ').reverse().join('.'),
        
        // Abreviações comuns
        username.split(' ').map(word => word.charAt(0)).join(''),
        username.split(' ').map(word => word.charAt(0)).join('.'),
        username.split(' ').map(word => word.charAt(0)).join('_'),
        
        // Variações de casamento
        username.charAt(0).toUpperCase() + username.slice(1),
        username.charAt(0).toLowerCase() + username.slice(1).toUpperCase()
    ];
    
    // Remove duplicatas e entradas vazias usando ES5
    var uniqueVariations = [];
    for (var i = 0; i < variations.length; i++) {
        var variation = variations[i];
        if (variation && variation.length > 0 && uniqueVariations.indexOf(variation) === -1) {
            uniqueVariations.push(variation);
        }
    }
    
    return uniqueVariations;
}
