// Palavras-chave e padrões de busca associados - EXPANDIDO v3.2
var searchPatterns = [
    // 🔞 Termos Adultos/OnlyFans
    'onlyfans', 'ofans', 'fansly', 'privacy', 'nudes', 'leaked', 'content creator', 
    'camgirl', 'camboy', 'camming', 'tip menu', 'cam4free', 'custom content',
    'nsfw', 'explicit', '18+', 'xxx', 'videos', 'dms open', 'payperview', 
    'sub4sub', 'content menu', 'buy my content', 'dm for prices', 'sell nudes',
    'fancentro', 'justforfans', 'manyvids', 'avnstars', 'ismygirl', 'pocketstars',
    'clipp store', 'iwantclips', 'modelhub', 'adultwork', 'loyalfans', 'unlokme',
    'nsfwfans', 'pornpayperview', 'eplay', 'chaturbate', 'stripchat', 'livejasmin',
    'myfreecams', 'bongacams', 'camsoda', 'camversity', 'flirt4free', 'camplace',
    'onlycam', 'justcamit', 'sexcamsplus', 'herbicepscam', 'camwhores', 'xhamsterlive',
    'join my vip', 'premium snapchat', 'private snap', 'fetish content', 'kink friendly',
    'creator', 'modelo', 'atriz', 'ator', 'conteúdo adulto', 'vídeos personalizados',
    'fotógrafa sensual', 'freelance model', 'ritmo intenso', 'findom', 'femdom',
    'dominatrix', 'submissiva', 'lingerie', 'sigiloso', 'webcam', 'renda extra',
    'ensaios', 'pacotes promocionais', 'conteúdo desbloqueado', 'semprecinto',
    'domingo tem', 'conteúdo especial', 'sigam', 'novinha', 'novinho', 'privacy br',
    'monetize seu conteúdo', 'produtor', 'atendimento vip', 'satisfeita', 'satisfeito',
    
    // 🟧 Escort/Acompanhantes
    'escort', 'acompanhantes', 'sugar baby', 'sugar daddy', 'gp', 'garota programa',
    'fatalmodel', 'skokka', 'lupanares', 'meetes', 'anunciart', 'easycompanions',
    'vivastreet', 'locanto', 'mileroticos', 'gatas', 'gponline', 'terapeuta',
    'cityoflove', 'massage republic', 'eurogirlsescort', 'hot.com.br', 'hookup',
    'encontreumgaroto', 'companheiros', 'massage', 'sensual', 'intimate',
    'acompanhante de luxo', 'massagista', 'massagem com final feliz', 'massoterapia',
    'massagem tântrica', 'terapêutica', 'relaxamento profundo', 'atendimento com local',
    'atendimento a domicílio', 'sigilo absoluto', 'com local', 'massagens', 'encontros',
    'terapia', 'sessão', 'sou acompanhante', 'discreto', 'discreta', 'discrição',
    'alto nível', 'motel', 'pernoite', 'luxo', 'top class', 'encontro', 'privacy',
    'convívio', 'presencial', 'agência', 'meninas', 'rapazes', 'atendimentos',
    'momento relaxante', 'belíssima', 'sem frescura', 'liberal', 'estilo namoradinha',
    
    // 🟨 Modelos/Portfolio/Casting
    'elite model', 'casting', 'portfolio', 'portfolio link', 'booking', 'hire me',
    'model profile', 'art nude', 'erotic photography', 'implied nude', 'fashion model',
    'behance', 'artstation', 'modelmayhem', 'viewbug', '500px', 'dribbble', 'deviantart',
    'vsco', 'pixpa', 'format', 'foliohd', 'canva', 'onemodelplace', 'portfoliobox',
    'photoshelter', 'zenfolio', 'photodeck', 'smugmug', 'carbonmade', 'krop',
    'backstage', 'starnow', 'castingnetworks', 'models.com', 'actorsaccess',
    'castingfrontier', 'exploretalent', 'newfaces', 'modelscouts', 'talenthouse',
    'modelo fotográfico', 'ensaio sensual', 'ensaio artístico', 'book fotográfico',
    'digital influencer', 'influenciador', 'influenciadora', 'criadora de conteúdo',
    'parcerias', 'business inquiries', 'colaborações', 'embaixadora', 'agenciada',
    'agência de modelos', 'freelancer', 'trabalhos', 'meu trabalho', 'figurante',
    'divulgação', 'comercial', 'publicidade', 'musa', 'muso', 'miss', 'representante',
    'assessoria', 'ensaio', 'book masculino', 'book feminino', 'plus size',
    
    // 🔷 Redes Sociais
    'instagram model', 'reels', 'tiktok viral', 'snap', 'snapcode', 'linktr.ee',
    'beacons.ai', 'carrd', 'linkinbio', 'check bio', 'link in bio', 'bio link',
    'youtube channel', 'twitch streamer', 'discord server', 'telegram channel',
    'vk profile', 'weheartit', 'ask.fm', 'curiouscat', 'yubo', 'bigo live',
    'siga', 'sigam', 'follow', 'follow me', 'seguir', 'curtir', 'compartilhar',
    'divulgar', 'direct', 'inbox', 'caixa de entrada', 'dm', 'pm', 'subscribe',
    'inscreva-se', 'inscrever', 'stories', 'destaque', 'highlights', 'lives',
    'ao vivo', 'transmissão', 'parceria', 'publi', 'divulgação', 'sorteio',
    'giveaway', 'mega sena', 'comentar', 'comentários', 'grupo vip', 'grupo fechado',
    'contato profissional', 'links', 'rede social', 'feed', 'perfil real',
    
    // 🟪 Imagens/Compartilhamento
    'imgur', 'imagefap', 'motherless', 'e621', 'furaffinity', 'rule34', 'xbooru',
    'gelbooru', 'danbooru', 'hypnohub', 'hentai foundry', '8muses', 'pixiv',
    'nhentai', 'pornpics', 'pornimg', 'leakgirls', 'r18', 'superhq',
    'album privado', 'fotos privadas', 'acervo', 'coleção', 'conteúdo vazado',
    'exclusivo', 'vip access', 'mega folder', 'mega link', 'compartilhe',
    'compartilhado', 'galeria', 'pasta', 'álbum completo', 'cloud storage',
    'drive link', 'wetransfer', 'google photos', 'shows gravados', 'sets',
    'photo set', 'photo dump', 'collab', 'fotolog', 'packs', 'fotinhas',
    'imagens', 'nudes compartilhados', 'packs', 'win', 'peitinho', 'nudes folder',
    
    // 🟫 Fóruns/Leak/Communities  
    'leak.sx', 'fapello', 'coomer.party', 'forumophilia', 'thefappeningblog',
    'celebleaks', '8kun', '4chan', 'redditside', 'realityforum', 'forum.xxx',
    'leaked.zone', 'anon-ib', 'nonude.club', 'r34porn', 'nsfw.xxx', 'vipergirls',
    'bdsmlr', 'mydirtyhobby', 'planetleak', 'torlinkbunker', 'nofacefreak_18',
    'darkf.app', 'spankbang', 'xvideos', 'xnxx', 'pornhub', 'xxxstreams', 'sxyprn',
    'fórum', 'forum', 'comunidade', 'grupo', 'servidor', 'channel', 'canal',
    'roms', 'leaks', 'vazou', 'vazado', 'descuido', 'oops', 'slips', 'hackeado',
    'invadido', 'gozofans', 'leaked dropbox', 'mega cloud', 'nudes vazados',
    'antes do of', 'before onlyfans', 'ex namorada', 'ex boyfriend', 'revenge',
    'backstage', 'imagens raras', 'exclusivas', 'som ambiente', 'sem cortes',
    'uncut', 'deleted', 'removido', 'censurado', 'uncensored', 'deep web',
    
    // 🌐 Termos Regionais BR
    'faz programa', 'acompanhante de luxo', 'acompanhante executiva', 'massagem com final feliz',
    'sigilo absoluto', 'sem frescura', 'sigiloso', 'liberal', 'privacy br', 'privacy brasil',
    'webcamgirl br', 'novinha', 'carioca', 'paulista', 'gaúcha', 'mineira', 'nordestina',
    'tesuda', 'safadinha', 'safadão', 'gostosa', 'gostoso', 'putaria', 'sacanagem',
    'casa das primas', 'close friends', 'só para amigos', 'garota de programa', 
    'acompanhante de luxo', 'namoradinha virtual', 'sexo virtual', 'atendo casais',
    
    // 🎯 Termos Gerais OSINT
    'hot', 'leak', 'leaked content', 'private content', 'exclusive content',
    'patreon', 'feetpics', 'feetfinder', 'feet pics', 'foot fetish',
    'cosplay lewd', 'cosplay nsfw', 'femboy', 'furry nsfw', 'hentai', 'r34',
    'rule34', 'anime girl', 'waifu', 'ahegao', 'ecchi', 'lewd', 'hentai girl',
    'backup account', 'second account', 'alt account', 'private account',
    'vip content', 'premium content', 'paid content', 'subscription', 'ppv',
    'tribute', 'cumtribute', 'cock tribute', 'rate', 'dick rate', 'sph',
    'privacy leak', 'filter bypass', 'dating profile', 'anúncio pessoal',
    'verificado', 'verified', 'blue check', 'selo azul', 'official', 'real',
    'paysite', 'monetização', 'monetized', 'sugardaddy', 'sugarbaby',
    'meetups', 'linkbio', 'allmylinks', 'sessão online', 'sextape', 'love hotel'
];
